# Generated by Django 4.2.20 on 2025-04-04 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
